name: Pull_Request_Checks

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Install NPM dependencies
        run: npm install --dev

      - name: Prettier Check
        run: npm run prettier:check
